/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MedConsent__factory } from "./MedConsent__factory";
export { NaiveBaseline__factory } from "./NaiveBaseline__factory";
