/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IConsentGateway } from "./IConsentGateway";
export type { ProxyAccessLayer } from "./ProxyAccessLayer";
