/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProxyAccessLayerInterface extends Interface {
  getFunction(
    nameOrSignature: "consentContract" | "proxyOwner" | "requestRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProxyAccessAttempt" | "ProxyDenied"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consentContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxyOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRecord",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "consentContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proxyOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestRecord",
    data: BytesLike
  ): Result;
}

export namespace ProxyAccessAttemptEvent {
  export type InputTuple = [
    recordId: string,
    provider: AddressLike,
    granted: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    provider: string,
    granted: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    provider: string;
    granted: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProxyDeniedEvent {
  export type InputTuple = [
    recordId: string,
    provider: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    provider: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    provider: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProxyAccessLayer extends BaseContract {
  connect(runner?: ContractRunner | null): ProxyAccessLayer;
  waitForDeployment(): Promise<this>;

  interface: ProxyAccessLayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consentContract: TypedContractMethod<[], [string], "view">;

  proxyOwner: TypedContractMethod<[], [string], "view">;

  requestRecord: TypedContractMethod<
    [recordId: string, provider: AddressLike],
    [
      [string, string, bigint] & {
        contentHash: string;
        ipfsPointer: string;
        createdAt: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consentContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxyOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestRecord"
  ): TypedContractMethod<
    [recordId: string, provider: AddressLike],
    [
      [string, string, bigint] & {
        contentHash: string;
        ipfsPointer: string;
        createdAt: bigint;
      }
    ],
    "nonpayable"
  >;

  getEvent(
    key: "ProxyAccessAttempt"
  ): TypedContractEvent<
    ProxyAccessAttemptEvent.InputTuple,
    ProxyAccessAttemptEvent.OutputTuple,
    ProxyAccessAttemptEvent.OutputObject
  >;
  getEvent(
    key: "ProxyDenied"
  ): TypedContractEvent<
    ProxyDeniedEvent.InputTuple,
    ProxyDeniedEvent.OutputTuple,
    ProxyDeniedEvent.OutputObject
  >;

  filters: {
    "ProxyAccessAttempt(string,address,bool,uint256)": TypedContractEvent<
      ProxyAccessAttemptEvent.InputTuple,
      ProxyAccessAttemptEvent.OutputTuple,
      ProxyAccessAttemptEvent.OutputObject
    >;
    ProxyAccessAttempt: TypedContractEvent<
      ProxyAccessAttemptEvent.InputTuple,
      ProxyAccessAttemptEvent.OutputTuple,
      ProxyAccessAttemptEvent.OutputObject
    >;

    "ProxyDenied(string,address,uint256)": TypedContractEvent<
      ProxyDeniedEvent.InputTuple,
      ProxyDeniedEvent.OutputTuple,
      ProxyDeniedEvent.OutputObject
    >;
    ProxyDenied: TypedContractEvent<
      ProxyDeniedEvent.InputTuple,
      ProxyDeniedEvent.OutputTuple,
      ProxyDeniedEvent.OutputObject
    >;
  };
}
