/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConsentGateway,
  IConsentGatewayInterface,
} from "../../ProxyAccessLayer.sol/IConsentGateway";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "recordId",
        type: "string",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "checkPermission",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "recordId",
        type: "string",
      },
    ],
    name: "getRecord",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConsentGateway__factory {
  static readonly abi = _abi;
  static createInterface(): IConsentGatewayInterface {
    return new Interface(_abi) as IConsentGatewayInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConsentGateway {
    return new Contract(address, _abi, runner) as unknown as IConsentGateway;
  }
}
