/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IConsentGateway__factory } from "./IConsentGateway__factory";
export { ProxyAccessLayer__factory } from "./ProxyAccessLayer__factory";
