/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxyAccessLayerSol from "./ProxyAccessLayer.sol";
export type { proxyAccessLayerSol };
export type { MedConsent } from "./MedConsent";
export type { NaiveBaseline } from "./NaiveBaseline";
export * as factories from "./factories";
export { MedConsent__factory } from "./factories/MedConsent__factory";
export { NaiveBaseline__factory } from "./factories/NaiveBaseline__factory";
export type { IConsentGateway } from "./ProxyAccessLayer.sol/IConsentGateway";
export { IConsentGateway__factory } from "./factories/ProxyAccessLayer.sol/IConsentGateway__factory";
export type { ProxyAccessLayer } from "./ProxyAccessLayer.sol/ProxyAccessLayer";
export { ProxyAccessLayer__factory } from "./factories/ProxyAccessLayer.sol/ProxyAccessLayer__factory";
