/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NaiveBaselineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRecord"
      | "getRecord"
      | "getRecordEmergency"
      | "grantPermission"
      | "patient"
      | "revokePermission"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PermissionGranted"
      | "PermissionRevoked"
      | "RecordAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRecord",
    values: [string, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordEmergency",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantPermission",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "patient", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokePermission",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "patient", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokePermission",
    data: BytesLike
  ): Result;
}

export namespace PermissionGrantedEvent {
  export type InputTuple = [
    recordId: string,
    provider: AddressLike,
    expiresAt: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    provider: string,
    expiresAt: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    provider: string;
    expiresAt: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionRevokedEvent {
  export type InputTuple = [
    recordId: string,
    provider: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    provider: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    provider: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordAddedEvent {
  export type InputTuple = [
    recordId: string,
    contentHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: string,
    contentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: string;
    contentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NaiveBaseline extends BaseContract {
  connect(runner?: ContractRunner | null): NaiveBaseline;
  waitForDeployment(): Promise<this>;

  interface: NaiveBaselineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecord: TypedContractMethod<
    [
      recordId: string,
      contentHash: BytesLike,
      ipfsPointer: string,
      wrappedKey: string
    ],
    [void],
    "nonpayable"
  >;

  getRecord: TypedContractMethod<
    [recordId: string, provider: AddressLike],
    [[string, string, bigint]],
    "view"
  >;

  getRecordEmergency: TypedContractMethod<
    [recordId: string],
    [[string, string]],
    "view"
  >;

  grantPermission: TypedContractMethod<
    [recordId: string, provider: AddressLike, durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  patient: TypedContractMethod<[], [string], "view">;

  revokePermission: TypedContractMethod<
    [recordId: string, provider: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecord"
  ): TypedContractMethod<
    [
      recordId: string,
      contentHash: BytesLike,
      ipfsPointer: string,
      wrappedKey: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordId: string, provider: AddressLike],
    [[string, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordEmergency"
  ): TypedContractMethod<[recordId: string], [[string, string]], "view">;
  getFunction(
    nameOrSignature: "grantPermission"
  ): TypedContractMethod<
    [recordId: string, provider: AddressLike, durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "patient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokePermission"
  ): TypedContractMethod<
    [recordId: string, provider: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PermissionGranted"
  ): TypedContractEvent<
    PermissionGrantedEvent.InputTuple,
    PermissionGrantedEvent.OutputTuple,
    PermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionRevoked"
  ): TypedContractEvent<
    PermissionRevokedEvent.InputTuple,
    PermissionRevokedEvent.OutputTuple,
    PermissionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RecordAdded"
  ): TypedContractEvent<
    RecordAddedEvent.InputTuple,
    RecordAddedEvent.OutputTuple,
    RecordAddedEvent.OutputObject
  >;

  filters: {
    "PermissionGranted(string,address,uint256,uint256)": TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;
    PermissionGranted: TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;

    "PermissionRevoked(string,address,uint256)": TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
    PermissionRevoked: TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;

    "RecordAdded(string,bytes32,uint256)": TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
    RecordAdded: TypedContractEvent<
      RecordAddedEvent.InputTuple,
      RecordAddedEvent.OutputTuple,
      RecordAddedEvent.OutputObject
    >;
  };
}
